### ISSUE TITLE
can you explain the following code for me?thank you!

### ISSUE THREAD

**Issue by becauseOf** [tomazas/k2-course#12]
public float eval(int n, float x[], float y[], float m[], float t) {
        if (t < x[0] || t > x[n - 1]) return 0.0f;

        int i = 1;
        while (t > x[i]) i++;

        float h = x[i] - x[i - 1];
        float t1 = x[i] - t;
        float t2 = t - x[i - 1];
        float p1 = t1 * t1 * t1 / 6.0f;
        float p2 = t2 * t2 * t2 / 6.0f;
        float s1 = y[i - 1] - m[i - 1] * h * h / 6.0f;
        float s2 = y[i] - m[i] * h * h / 6.0f;
        return (m[i - 1] * p1 + m[i] * p2 + s1 * t1 + s2 * t2) / h;
    }

**Comment by tomazas** [comment]
Check some comments at: https://github.com/tomazas/k2-course/blob/ffc7955b9b866941a4deb0906d2900857ef6722e/src/Splainas.java#L118

**Comment by becauseOf** [comment]
Thank you so much!
